.\" Manpage for battleship-cobol.
.\" Contact gsteixei@gmail.com to correct errors or typos.
.TH man 6 "23 May 2021" "0.5" "Battleship Cobol man page"
.SH NAME
battleship \- Start the Battleship game
.SH SYNOPSIS
battleship
.SH DESCRIPTION
The classical Battleship game made in Cobol. Also known as Naval Battle, it is a strategy game that is played on ruled grids where each player's fleet of ships are marked. The location of the ships are concealed from the other player.
Players alternate turns, shooting at the other player's ships, the objective is to destroy the opposing player's fleet.
.SH HOW TO PLAY
Make your shots typing a letter and a number that represents the desired target location.
    Eg. A 1, B 3, C 4,...
.SH OPTIONS
    The battleship does not take any options.
.SH SEE ALSO
    gnucobol(6)
.SH BUGS
    No known bugs.
.SH AUTHOR
    Gustavo Selbach Teixeira (gsteixei@gmail.com)
